# set up and configure Debian via Ansible
# run with --ask-become-pass
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Load required deb files as a list
      ansible.builtin.set_fact:
        apt_package_list: "{{ lookup('file', './apt-package-list').splitlines() }}"

    - name: Install required packages with dpkg
      ansible.builtin.apt:
        name: "{{ apt_package_list }}"
        update_cache: yes
        state: latest
      become: true
      become_user: root

    - name: Load required flatpaks as a list
      ansible.builtin.set_fact:
        flatpak_package_list: "{{ lookup('file', './flatpak-package-list').splitlines() }}"

    - name: Install flatpaks
      community.general.flatpak:
        name: "{{ flatpak_package_list }}"
        state: present
